apiVersion: v1
kind: Service
metadata:
  name: stockquote
  labels:
    name: stockquote
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
    # the port that this service should serve on
    - port: 8080

  type: NodePort
  selector:
    name: stockquote